sudo: requried

matrix:
  include:
    # - os: linux
    #   services: docker
    - os: osx

install:
  - cd $TRAVIS_BUILD_DIR
  - source ./.travis/install.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - source ./.travis/script.sh
