
branches:
  only:
    - master
  except:
    - gh-pages

clone_folder: c:\projects\lightmetrica-v2

environment:
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
  TBB_ROOT: C:\projects\lightmetrica-v2\external\src\tbb44_20150928oss
  TBB_ARCH_PLATFORM: intel64

install:
  - git clone https://github.com/hi2p-perim/lightmetrica-v2-external.git C:\projects\lightmetrica-v2\external

build_script:
  - cd C:\projects\lightmetrica-v2
  - md build
  - cd build
  - cmake -G "Visual Studio 14 Win64" ..
  - msbuild /m /p:Configuration=Release /p:Platform=x64 lightmetrica.sln

test_script:
  - cd bin\Release
  - lightmetrica.exe