
branches:
  only:
    - master
  except:
    - gh-pages

clone_folder: c:\projects\lightmetrica-v2

environment:
  BOOST_INCLUDEDIR: c:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\lib64-msvc-14.0
  TBB_ROOT: c:\projects\lightmetrica-v2\external\src\tbb44_20150928oss
  TBB_ARCH_PLATFORM: intel64

init:
  - cmake -E remove -f c:\programdata\chocolatey\bin\cpack.exe

install:
  - choco install git-lfs.install -version 1.1.0
  - git clone --depth=1 https://github.com/hi2p-perim/lightmetrica-v2-external.git C:\projects\lightmetrica-v2\external
  - git clone --depth=1 https://github.com/hi2p-perim/lightmetrica-v2-example.git C:\projects\lightmetrica-v2\example
  - rd /s /q C:\projects\lightmetrica-v2\example\.git
  - del /s /q C:\projects\lightmetrica-v2\example\.gitattributes

build_script:
  - cd C:\projects\lightmetrica-v2
  - md build
  - cd build
  - cmake -G "Visual Studio 14 Win64" ..
  - msbuild /m /p:Configuration=Release /p:Platform=x64 lightmetrica.sln
  - cpack -G "ZIP"

artifacts:
  - path: 'build\*.zip'
    name: lightmetrica-v2-latest
